### ISSUE TITLE
Returning invalid client credential as I'm passing correct username and password

### ISSUE THREAD

**Issue by akhilesh-systango** [SwiftDil/swiftdil-postman#1]
![screen shot 2018-07-02 at 12 06 49 am](https://user-images.githubusercontent.com/40065869/42137554-dfff1216-7d8b-11e8-81f0-2677e54cd15b.png)

**Comment by MoSwiftDil** [comment]
Hi @akhilesh-systango ,

The username should be your API **Client ID**, rather than the Web Portal **Username**. The password should be the API **Client Key** provided.

Please try and let me know if you are still facing issues.

Regards
